services:
  mysql:
    image: mysql:latest
    platform: linux/x86_64
    container_name: fraud_detection_mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: fraud_detection
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - fraud_detection_network

networks:
  fraud_detection_network:
    driver: bridge

volumes:
  mysql_data: 
